export const AUTH_USER = 'AUTH_USER',
    UNAUTH_USER = 'UNAUTH_USER',
    AUTH_ERROR = 'AUTH_ERROR',
    PROTECTED_TEST = 'PROTECTED_TEST',
    REQUEST_TO_SERVER = 'REQUEST_TO_SERVER',
    GET_STATS = "GET_STATS",
    GET_PROFILE = "GET_PROFILE",
    TEST_ACTION = 'TEST_ACTION',
    ADD_TOKEN = "ADD_TOKEN",
    GET_INFO_ERROR = "GET_INFO_ERROR";



export const FETCH_USER_VACCINE_DATA_SUCCESS = "FETCH_USER_VACCINES_DATA_SUCCESS";